const POS={US:[24,43],GB:[44,31],DE:[51,35],CH:[48,39],JP:[86,43],CN:[78,50],HK:[82,55],SG:[80,68],AU:[88,82],CA:[18,34],AE:[61,59],IN:[70,61]};
const CENTRES={US:['New York','America/New_York',9,16],GB:['London','Europe/London',8,16.5],DE:['Frankfurt','Europe/Berlin',8,17],CH:['Zurich','Europe/Zurich',8,17],JP:['Tokyo','Asia/Tokyo',9,15],CN:['Shanghai','Asia/Shanghai',9.5,15],HK:['Hong Kong','Asia/Hong_Kong',9.5,16],SG:['Singapore','Asia/Singapore',9,17],AU:['Sydney','Australia/Sydney',10,16],CA:['Toronto','America/Toronto',9.5,16],AE:['Dubai','Asia/Dubai',10,14],IN:['Mumbai','Asia/Kolkata',9.25,15.5]};
let DATA=null,selected='US';
const fmt=v=>{if(v==null)return '—';const a=Math.abs(v);return `${v<0?'−':v>0?'+':''}$${a>=1e12?(a/1e12).toFixed(2)+'T':a>=1e9?(a/1e9).toFixed(1)+'B':a>=1e6?(a/1e6).toFixed(0)+'M':a.toFixed(0)}`};
function hour(zone){const parts=new Intl.DateTimeFormat('en-GB',{timeZone:zone,hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date());return +parts.find(x=>x.type==='hour').value + +parts.find(x=>x.type==='minute').value/60}
function open(code){const c=CENTRES[code];if(!c)return false;const h=hour(c[1]);return h>=c[2]&&h<c[3]}
function score(v,max){if(!max)return 50;return Math.round(50+45*Math.max(-1,Math.min(1,v/max)))}
function render(){const rows=DATA.economies.filter(x=>POS[x.code]);const max=Math.max(...rows.map(x=>Math.abs(x.value||0)),1);rows.forEach(x=>x.score=score(x.value,max));const avg=Math.round(rows.reduce((a,b)=>a+b.score,0)/rows.length);document.querySelector('#pulse').textContent=avg;document.querySelector('#regime').textContent=avg>57?'INFLOW BIAS':avg<43?'OUTFLOW BIAS':'BALANCED';document.querySelector('#pointer').style.left=`${avg}%`;document.querySelector('#period').textContent=`OBSERVATION WINDOW · ${DATA.referenceYear}`;document.querySelector('#fresh').textContent=`UPDATED ${new Date(DATA.generatedAt).toLocaleDateString('en-GB',{day:'2-digit',month:'short'}).toUpperCase()}`;
const svg=document.querySelector('#map');svg.querySelectorAll('.flow').forEach(x=>x.remove());const pos=rows.filter(x=>x.value>0).sort((a,b)=>b.value-a.value).slice(0,4),neg=rows.filter(x=>x.value<0).sort((a,b)=>a.value-b.value).slice(0,4);neg.forEach((a,i)=>{const b=pos[i%pos.length];if(!b)return;const [x1,y1]=POS[a.code],[x2,y2]=POS[b.code];const p=document.createElementNS('http://www.w3.org/2000/svg','path');const X1=x1*12,Y1=y1*6.1,X2=x2*12,Y2=y2*6.1,cy=Math.min(Y1,Y2)-70-i*10;p.setAttribute('d',`M${X1} ${Y1} Q${(X1+X2)/2} ${cy} ${X2} ${Y2}`);p.setAttribute('class','flow inflow');svg.appendChild(p)});
const nodes=document.querySelector('#nodes');nodes.innerHTML='';rows.forEach(x=>{const [px,py]=POS[x.code];const d=document.createElement('div');d.className=`node ${open(x.code)?'awake':''} ${x.value>=0?'positive':'negative'}`;d.style.left=px+'%';d.style.top=py+'%';d.innerHTML=`<div class="node-dot"></div><label>${x.code} · ${x.score}</label><small>${CENTRES[x.code][0]}</small>`;d.onclick=()=>{selected=x.code;detail()};nodes.appendChild(d)});detail();ranking(rows);sessions();tape(rows)}
function detail(){const x=DATA.economies.find(v=>v.code===selected)||DATA.economies[0];const s=x.score||50;document.querySelector('#detail').innerHTML=`<span class="countrycode">${x.code} / ${CENTRES[x.code]?.[0]||'CAPITAL ZONE'}</span><h3>${x.name}</h3><div class="metric"><span>Flow pressure</span><b>${s}/100</b></div><div class="signalbar"><i style="width:${s}%"></i></div><div class="metric"><span>Observed portfolio investment, net</span><b>${fmt(x.value)}</b></div><div class="metric"><span>Reference year</span><b>${x.year||DATA.referenceYear}</b></div><div class="metric"><span>Market session</span><b>${open(x.code)?'AWAKE':'CLOSED'}</b></div><p class="explain">A score above 50 indicates stronger positive net portfolio-investment pressure relative to the covered cross-section; below 50 indicates negative pressure. This is a normalized BondStats signal, not a forecast or a bilateral transaction measure.</p>`}
function ranking(rows){const sorted=[...rows].sort((a,b)=>Math.abs(b.score-50)-Math.abs(a.score-50)).slice(0,8);document.querySelector('#ranking').innerHTML=sorted.map((x,i)=>`<div class="ranking-row"><span class="n">${String(i+1).padStart(2,'0')}</span><strong>${x.name}</strong><span class="val">${fmt(x.value)}</span><span class="state ${x.score>=50?'pos':'neg'}">${x.score>=50?'INFLOW':'OUTFLOW'}</span></div>`).join('')}
function sessions(){document.querySelector('#sessions').innerHTML=Object.entries(CENTRES).map(([c,v])=>`<div class="sessionrow ${open(c)?'open':''}"><b>${v[0]}</b><span>${open(c)?'AWAKE':'CLOSED'}</span><small>${new Intl.DateTimeFormat('en-GB',{timeZone:v[1],hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date())} local</small></div>`).join('');document.querySelector('#utcdate').textContent=new Date().toISOString().slice(0,10)}
function tape(rows){const awake=rows.filter(x=>open(x.code)).map(x=>CENTRES[x.code][0]).slice(0,5);const top=[...rows].sort((a,b)=>b.score-a.score)[0],low=[...rows].sort((a,b)=>a.score-b.score)[0];document.querySelector('#tape').innerHTML=`<span><b>CAPITAL AWAKE</b> ${awake.join(' · ')||'SESSION HANDOFF'}</span><span><b>STRONGEST ATTRACTION</b> ${top?.code||'—'} ${top?.score||'—'}</span><span><b>STRONGEST RELEASE</b> ${low?.code||'—'} ${low?.score||'—'}</span><span><b>DATA</b> WORLD BANK OPEN DATA · CC BY 4.0</span>`}
function tick(){document.querySelector('#clock').textContent=new Date().toISOString().slice(11,16)+' UTC'}
fetch('./data/flows.json',{cache:'no-store'}).then(r=>r.json()).then(d=>{DATA=d;render();tick();setInterval(()=>{tick();sessions()},60000)}).catch(()=>{document.querySelector('#fresh').textContent='DATA UNAVAILABLE'});
